{
  "additionalMetadata": {
    "cna": "mitre",
    "cveId": "CVE-2023-41105",
    "description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
    "reason": "Improve version ranges to indicate fix",
    "references": [
      "https://github.com/python/cpython/issues/106242",
      "https://github.com/python/cpython/pull/107981",
      "https://github.com/python/cpython/pull/107982",
      "https://github.com/python/cpython/pull/107983",
      "https://mail.python.org/archives/list/security-announce%40python.org/thread/D6CDW3ZZC5D444YGL3VQUY6D4ECMCQLD/",
      "https://security.netapp.com/advisory/ntap-20231006-0015/"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://github.com",
        "cpes": [
          "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
        ],
        "packageName": "python/cpython",
        "product": "CPython",
        "repo": "https://github.com/python/cpython",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThan": "3.12.0rc2",
            "status": "affected",
            "version": "3.12.0a1",
            "versionType": "python"
          },
          {
            "lessThan": "3.11.5",
            "status": "affected",
            "version": "3.11.0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}