{
  "additionalMetadata": {
    "cna": "snyk",
    "cveId": "CVE-2024-21503",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/psf/black/commit/f00093672628d212b8965a8993cee8bedf5fe9b8",
      "https://github.com/psf/black/releases/tag/24.3.0",
      "https://security.snyk.io/vuln/SNYK-PYTHON-BLACK-6256273"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:psf:black:*:*:*:*:*:*:*:*"
        ],
        "packageName": "black",
        "packageType": "python",
        "product": "black",
        "repo": "https://github.com/psf/black",
        "vendor": "Python Software Foundation",
        "versions": [
          {
            "lessThan": "24.3.0",
            "status": "affected",
            "version": "0",
            "versionType": "semver"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}