{
  "additionalMetadata": {
    "cna": "postgresql",
    "cveId": "CVE-2024-4216",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/pgadmin-org/pgadmin4/issues/7282"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:pgadmin:pgadmin:*:*:*:*:*:postgresql:*:*",
          "cpe:2.3:a:pgadmin:pgadmin_4:*:*:*:*:*:postgresql:*:*"
        ],
        "packageName": "pgAdmin4",
        "product": "pgAdmin 4",
        "repo": "https://github.com/pgadmin-org/pgadmin4",
        "vendor": "pgadmin.org",
        "versions": [
          {
            "lessThan": "8.6",
            "status": "affected",
            "version": "0",
            "versionType": "custom"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}