{
  "additionalMetadata": {
    "cna": "github_m",
    "cveId": "CVE-2024-35195",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
      "https://github.com/psf/requests/pull/6655",
      "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
    ]
  },
  "adp": {
    "affected": [
      {
        "collectionURL": "https://pypi.org",
        "cpes": [
          "cpe:2.3:a:python:requests:*:*:*:*:*:python:*:*"
        ],
        "packageName": "requests",
        "packageType": "python",
        "product": "requests",
        "vendor": "psf",
        "versions": [
          {
            "lessThan": "2.32.0",
            "status": "affected",
            "version": "0",
            "versionType": "python"
          }
        ]
      }
    ],
    "providerMetadata": {
      "orgId": "00000000-0000-4000-8000-000000000000",
      "shortName": "anchoreadp"
    }
  }
}